### ISSUE TITLE
lapels error : IndexError: list index out of range

### ISSUE THREAD

**Issue by AlicePsyche** [holtjma/suspenders#3]
Hi, 

After mapping to Pseudogenomes, the next step is reference conversion. When I run `pylapels -n -p 8 -f -o ./AB_align.bam ./AB_genome/AB.mod ./AB_AlignmentDir/accepted_hits.bam`, I got the following error messages:

```
Traceback (most recent call last):
  File "/data4/bingjie/software/anaconda/bin/pylapels", line 4, in <module>
    __import__('pkg_resources').run_script('lapels==1.0.7', 'pylapels')
  File "/software/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script

  File "/software/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script

  File "/software/anaconda/lib/python2.7/site-packages/lapels-1.0.7-py2.7.egg/EGG-INFO/scripts/pylapels", line 386, in <module>

  File /software/anaconda/lib/python2.7/site-packages/lapels-1.0.7-py2.7.egg/EGG-INFO/scripts/pylapels", line 247, in run

IndexError: list index out of range
```

I used the same mod file which I used to generate pseudogenomes, the bam file is also OK. I have run pylapels before( although with wrong chromosome name "1"/"chr1") and there was no problem.

**Comment by holtjma** [comment]
AlicePsyche,

Since this seems to be a problem with the Lapels install, I'm going to ask you open a ticket with Lapels.  I've contacted the author, so he knows you'll be submitting issues.

Here's the link: https://github.com/shunping/lapels

**Comment by AlicePsyche** [comment]
The lapels I used now is `pylapels 0.2.0 in Lapels 1.0.7`. This version works OK(at least there is no error report before, as you know, I have done the reference conversion with the wrong chromosome name "1"/"chr1" ) but now when I tried to use it with the right pseudogenome files, I got the 'IndexError: list index out of range' error message.
